controllers/home.py
from flask import Flask, abort, render_template, request, redirect, url_for, Blueprint
from models.Post import Post
from models.Comment import Comment
from models.Author import Author
from models.Tag import Tag
from forms import EmailForm
from forms import SearchForm
import BusinessLogicLayer.businesslogic
import random
import bleach


home_blueprint = Blueprint('home', __name__)


# Function to get spotlight posts for a randomly selected topic
def get_spotlight_posts():
    topics = BusinessLogicLayer.businesslogic.gettags()
    topic_names = [topic.name for topic in topics]
    spotlight = random.sample(topics, 1)[0]
    spotlightposts = BusinessLogicLayer.businesslogic.get_posts_by_tag(spotlight.id)

    if(len(spotlightposts) > 3):
        spotlightposts = random.sample(spotlightposts, 3)

    return {'topic': spotlight, 'posts': spotlightposts}                        


# Route for the home page
@home_blueprint.route('/index')
def index():
    searchform = SearchForm()

    # Retrieve the list of posts from the database, and shuffle
    posts = BusinessLogicLayer.businesslogic.getposts()
    random.shuffle(posts)

    topics = BusinessLogicLayer.businesslogic.gettags()
    topic_names = [topic.name for topic in topics]
    spotlight = get_spotlight_posts()

    featured_post = random.choice(posts)

    # Pass the list of posts to the view for rendering
    return render_template('/index.html', posts=posts, topic_selection = topic_names, spotlight_posts = spotlight['posts'], spotlight_topic = spotlight['topic'].name, searchform=searchform, featured_post = featured_post)


# Route for the about page
@home_blueprint.route('/about')
def about():
    authors = BusinessLogicLayer.businesslogic.getauthors()

    searchform = SearchForm()
    spotlight = get_spotlight_posts()

    # Pass the list of posts to the view for rendering
    return render_template('/about.html', authors=authors, spotlight_topic = spotlight['topic'].name, spotlight_posts = spotlight['posts'],  searchform = searchform)


# Route for the mailing list page
@home_blueprint.route('/mailinglist', methods=['GET', 'POST'])
def mailinglist():
    form = EmailForm()

    searchform = SearchForm()
    spotlight = get_spotlight_posts()

    if form.validate_on_submit():
        # Clean the email input
        email = bleach.clean(form.email.data)

        # Process the email here (e.g., add it to the mailing list)

        # Redirect to a success page or the mailing list page
        return redirect(url_for('home.mailinglist'))

    return render_template('/mailinglist.html', form=form, spotlight_topic = spotlight['topic'].name, spotlight_posts = spotlight['posts'],  searchform = searchform)


# Route for the website entry point
@home_blueprint.route('/')
def entry():
    return redirect(url_for('home.index'))

controllers/search.py
from flask import Flask, abort, render_template, request, redirect, url_for, Blueprint
from models.Post import Post
from models.Comment import Comment
from models.Author import Author
from models.Tag import Tag
from forms import SearchForm
from controllers.home import get_spotlight_posts
import BusinessLogicLayer.businesslogic
import random

search_blueprint = Blueprint('search', __name__)


# Route for handling search functionality
@search_blueprint.route('/search', methods=['GET', 'POST'])
def search():
    form = SearchForm()

    # get sidebar resources
    sidebar_searchform = SearchForm()
    spotlight = get_spotlight_posts()

    search_query = form.query.data
    if(search_query is None):
        search_query = ''

    # If the form is valid, perform the search and render the search results
    if form.validate_on_submit():

        # Find a list of posts relevant to the search
        filteredposts = BusinessLogicLayer.businesslogic.post_search(search_query)

        return render_template('/postsearch.html', posts=filteredposts, originalsearch=search_query, form=form, spotlight_topic = spotlight['topic'].name, spotlight_posts = spotlight['posts'],  searchform = sidebar_searchform)

    return render_template('/postsearch.html', posts=[], originalsearch=search_query, form=form, spotlight_topic = spotlight['topic'].name, spotlight_posts = spotlight['posts'],  searchform = sidebar_searchform)

templates/about.html
<!DOCTYPE HTML>
<!--
	based on Editorial by HTML5 UP
-->
<html>
	<head>
		<title>About - Blogueuse</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{{ url_for('static', filename='assets/css/main.css') }}">
	</head>
	<body class="is-preload">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Main -->
					<div id="main">
						<div class="inner">

							<!-- Header -->
								<header id="header">
									<a href="{{ url_for('home.index') }}" class="logo"><strong>Blogueuse</strong> find your niche</a>
								</header>

							<!-- Banner -->
								<section id="banner">
									<div class="content">
										<header>
											<h1>Meet the Team</h1>
											<p>Get to know our all-star writers</p>
										</header>
										<p>Learn more about the talented and passionate writers who bring our content to life. Our diverse team of contributors covers a wide range of topics, from spirituality and astrology to productivity and gaming, ensuring that we offer something for everyone. Each writer brings their unique perspective and expertise to create engaging, informative, and inspiring articles, providing our readers with a wealth of knowledge and insight. Get to know the dedicated individuals behind the articles you love, and explore their bios to learn more about their passions, experiences, and contributions to our community.</p>
									</div>
								</section>
							
							<!-- Authors Section -->
								<section>
									<header class="major">
										<h2>Contributors</h2>
									</header>
									<div class="posts">
										
									{% for author in authors %}
									<article>
										<a href="#" class="image"><img src="{{ url_for('static', filename='images/author/' ~ author.name.replace(' ', '_') ~ '.jpg') }}" alt="" /></a>
										<header>
											<h3>{{ author.name }}</h3>
											<p>{{author.role}}</p>
										</header>
										<p>{{ author.bio }}</p>
									</article>
									{% endfor %}
					
									</div>
								</section>
						</div>
					</div>

				<!-- Sidebar -->
				{% include 'sidebar.html' %}
			</div>
		
			<script src="{{ url_for('static', filename='assets/js/jquery.min.js') }}"></script>
			<script src="{{ url_for('static', filename='assets/js/browser.min.js') }}"></script>
			<script src="{{ url_for('static', filename='assets/js/breakpoints.min.js') }}"></script>
			<script src="{{ url_for('static', filename='assets/js/util.js') }}"></script>
			<script src="{{ url_for('static', filename='assets/js/main.js') }}"></script>
		
	</body>
</html>

templates/index.html
<!DOCTYPE HTML>
<!--
	based on Editorial by HTML5 UP
-->
<html>

<head>
	<title>Home - Blogueuse</title>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
	<link rel="stylesheet" href="{{ url_for('static', filename='assets/css/main.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='csscustom/style.css') }}" />
</head>

<body class="is-preload">

	<!-- Wrapper -->
	<div id="wrapper">

		<!-- Main -->
		<div id="main">
			<div class="inner">

				<!-- Header  -->
				<header id="header">
					<a href="{{ url_for('home.index') }}" class="logo"><strong>Blogueuse</strong> find your niche</a>
				</header>

				<!-- Banner -->
				<section id="banner">
					<div class="content">
						<header>
							<h2><strong>Featured post</strong><br /></h2>
							<h3>{{featured_post.title}}</h3>
							<p>{{featured_post.author.name}}</p>
						</header>
						<p>{{featured_post.preview}}</p>
						<ul class="actions">
							<li><a href="{{ url_for('post.show_post', post_id=featured_post.id) }}"
									class="button big">Read Now</a></li>
						</ul>
					</div>
					<span class="image object">
						<a><img src="{{ url_for('static', filename='images/posts_small/' ~ featured_post.id ~ '.jpg') }}" /></a>
					</span>
				</section>
			
				<!-- Top topic Section -->
				<section>
					<header class="major">
						<h2>What's your Passion?</h2>
					</header>
					<div class="features">
						{% for topic in topic_selection %}
						<article class="topic-article">
							<div class="content">
								<h3>{{ topic }}</h3>
								<form method="POST" action="{{ url_for('search.search') }}">
									{{ searchform.csrf_token }}
									<input type="hidden" name="query" value="{{ topic }}" />
									<button type="submit" onclick="this.form.submit();">
										<img src="{{ url_for('static', filename='images/icons/' ~ topic ~ '.jpg') }}" alt="Custom Image"/>
									</button>
								</form>
							</div>
						</article>
						{% endfor %}
					</div>
				</section>

				<!-- Posts Section -->
				<section>
					<header class="major">
						<h2>Recent posts</h2>
					</header>
					<div class="posts">
						{% for post in posts %}
						<article>
							<a href="{{ url_for('post.show_post', post_id=post.id) }}" class="image"><img
									src="{{ url_for('static', filename='images/posts_small/' ~ post.id ~ '.jpg') }}"
									alt="" /></a>
							<header>
								<h3>{{ post.title }}</h3>
								<p>By {{post.author.name}}</p>
							</header>
							<p>{{ post.preview }}</p>
						</article>
						{% endfor %}
					</div>
				</section>
			</div>
		</div>
		{% include 'sidebar.html' %}
	</div>
	<script src="{{ url_for('static', filename='assets/js/jquery.min.js') }}"></script>
	<script src="{{ url_for('static', filename='assets/js/browser.min.js') }}"></script>
	<script src="{{ url_for('static', filename='assets/js/breakpoints.min.js') }}"></script>
	<script src="{{ url_for('static', filename='assets/js/util.js') }}"></script>
	<script src="{{ url_for('static', filename='assets/js/main.js') }}"></script>
</body>

</html>

templates/mailinglist.html
<!DOCTYPE HTML>
<!--
	based on Editorial by HTML5 UP
-->
<html>
	<head>
		<title>Mailing List - Blogueuse</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{{ url_for('static', filename='assets/css/main.css') }}">
	</head>
	<body class="is-preload">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Main -->
					<div id="main">
						<div class="inner">

							<!-- Header -->
								<header id="header">
									<a href="{{ url_for('home.index') }}" class="logo"><strong>Blogueuse</strong> find your niche</a>
								</header>

							<!-- Banner -->
								<section id="banner">
									<div class="content">
										<header>
											<h1>Join our Mailing List Today</h1>
											<p>Free, High-Quality Content</p>
										</header>
										<p>Don't miss out on the latest articles, insights, and updates from our talented team of writers. By joining our mailing list, you'll receive a carefully curated selection of content tailored to your interests, delivered straight to your inbox.</p>
										<p>Here's what you can expect when you sign up:</p>
										<p>Exclusive Access: Be the first to read our latest articles, interviews, and in-depth guides on a wide range of topics, from spirituality and astrology to productivity and gaming.</p>
										<p>Personalized Recommendations: Based on your preferences, we'll send you a handpicked selection of articles that we believe will resonate with you and inspire your personal journey.</p>
										<p>Special Offers and Invitations: Enjoy exclusive discounts, promotions, and invitations to special events, webinars, and workshops hosted by our team and guest experts.</p>
										<p>Community Connection: Engage with like-minded individuals, share your thoughts and experiences, and be part of a supportive community that values knowledge, curiosity, and personal growth.</p>
										<p>Joining our mailing list is quick and easy! Simply enter your email address below and select your areas of interest. We respect your privacy and promise never to spam you or share your information with third parties.</p>
										<p>Sign up today and embark on a journey of exploration, inspiration, and personal growth with our incredible team of writers and experts!</p>
										<p>Enter your email address below, and a confirmation email will be sent to your account:</p>
										
										<!-- Search -->
										<!-- type="email" for native browser validation -->
										<section id="email" class="alt">
											<form method="post" action="{{ url_for('home.mailinglist') }}">
												{{ form.hidden_tag() }}
												{{ form.email(placeholder="Your Email Address", id="query", required="required", type="email") }}
												{% if form.email.errors %}
												<ul class="validation-errors">
													{% for error in form.email.errors %}
														<li>{{ error }}</li>
													{% endfor %}
												</ul>
												{% endif %}
												{{ form.submit(style="margin-top: 10px;") }}
											</form>
										</section>										
									</div>
									<span class="image object">
										<img src="{{ url_for('static', filename='images/mail_tall.jpg') }}" alt="">
									</span>
								</section>							
						</div>
					</div>
				<!-- Sidebar -->
				{% include 'sidebar.html' %}
			</div>
		
			<script src="{{ url_for('static', filename='assets/js/jquery.min.js') }}"></script>
			<script src="{{ url_for('static', filename='assets/js/browser.min.js') }}"></script>
			<script src="{{ url_for('static', filename='assets/js/breakpoints.min.js') }}"></script>
			<script src="{{ url_for('static', filename='assets/js/util.js') }}"></script>
			<script src="{{ url_for('static', filename='assets/js/main.js') }}"></script>
	</body>
</html>

templates/postdetail.html
<!DOCTYPE HTML>
<!--
	based on Generic by HTML5 UP
-->
<html>

<head>
	<title>Post - Blogueuse</title>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
	<link rel="stylesheet" href="{{ url_for('static', filename='assets/css/main.css') }}" />
	<link rel="stylesheet" href="{{ url_for('static', filename='csscustom/style.css') }}" />
</head>

<body class="is-preload">

	<!-- Wrapper -->
	<div id="wrapper">

		<!-- Main -->
		<div id="main">
			<div class="inner">

				<!-- Header -->
				<header id="header">
					<a href="{{ url_for('home.index') }}" class="logo"><strong>Blogueuse</strong> find your niche</a>
				</header>

				<!-- Content -->
				<section>
					<header class="main">
						<h1>{{ post.title }}</h1>
					</header>
					<span class="image main"><img
							src="{{ url_for('static', filename='images/posts_large/' ~ post.id ~ '.jpg') }}"
							alt="" /></span>
					{% for block in post.content.split('\n\n') %}
					<p>{{ block }}</p>
					{% endfor %}
					<p>By {{author.name}}, {{author.role}}<br>Image via {% if post.id == 6 or post.id == 11  or post.id == 7 or post.id == 3 or post.id == 14 or post.id == 15 %}Unsplash{% else %}Stable Diffusion{% endif %}</p>
				</section>

				<!--Comments Section-->
				<section>
					<!-- COMMENT FORM-->
					<header>
						<h3>Your Thoughts?</h3>
						<p>At Blogueuse, we value every opinion -- even yours</p>
						<!-- be a part of the conversation -->
					</header>
					<section id="comment-form" class="alt">
						<form method="post" action="{{ url_for('post.show_post', post_id=post.id) }}">
							{{ form.hidden_tag() }}

							{{ form.comment.label }} {{ form.comment() }}
							{% if form.comment.errors %}
							<ul>
								{% for error in form.comment.errors %}
								<li>{{ error }}</li>
								{% endfor %}
							</ul>
							{% endif %}

							{{ form.name.label(class_="field-name", style="padding-top: 10px;") }} {{ form.name(class_="field-name-box") }}
							{% if form.name.errors %}
							<ul>
								{% for error in form.name.errors %}
								<li>{{ error }}</li>
								{% endfor %}
							</ul>
							{% endif %}

							{{ form.recaptcha }}
							{% if form.recaptcha.errors %}
							<ul>
								{% for error in form.recaptcha.errors %}
								<li>{{ error }}</li>
								{% endfor %}
							</ul>
							{% endif %}
							<input type="submit" value="Submit" style="margin-top: 10px;">
						</form>
					</section>

					<!-- Comments Section -->
					<header class="major">
						<h2>Comments</h2>
					</header>
					<div class="features">
						{% for comment in post.comments %}
						<article>
							<div class="content">
								<h3>{{comment.author}}</h3>
								<p>{{comment.content}}</p>
							</div>
						</article>
						<article></article>
						{% endfor %}
					</div>
				</section>
			</div>
		</div>
		<!-- Sidebar -->
		{% include 'sidebar.html' %}
	</div>

	<!-- Scripts -->
	<script src="{{ url_for('static', filename='assets/js/jquery.min.js') }}"></script>
	<script src="{{ url_for('static', filename='assets/js/browser.min.js') }}"></script>
	<script src="{{ url_for('static', filename='assets/js/breakpoints.min.js') }}"></script>
	<script src="{{ url_for('static', filename='assets/js/util.js') }}"></script>
	<script src="{{ url_for('static', filename='assets/js/main.js') }}"></script>
</body>

</html>

templates/postsearch.html
<!DOCTYPE HTML>
<!--
	based on Editorial by HTML5 UP
-->
<html>

<head>
	<title>Post Search - Blogueuse</title>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
	<link rel="stylesheet" href="{{ url_for('static', filename='assets/css/main.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='csscustom/style.css') }}" />
	<script src="{{ url_for('static', filename='jscustom/scripts.js') }}"></script>
</head>

<body class="is-preload">

	<!-- Wrapper -->
	<div id="wrapper">

		<!-- Main -->
		<div id="main">
			<div class="inner">

				<!-- Header -->
				<header id="header">
					<a href="{{ url_for('home.index') }}" class="logo"><strong>Blogueuse</strong> find your niche</a>
				</header>


				<!-- Section for search and posts -->
				<section id="search" class="alt">
					<div class="search-center">
						<form method="post" action="{{ url_for('search.search') }}">
							{{ form.hidden_tag() }}
							{{ form.query(placeholder="Make a New Search", id="query", required="required",
							oninput="toggleSearchButton()") }}
							{{ form.submit(id="search-btn", style="display:none;" + "margin-top: 5px;") }}
						</form>
					</div>
				</section>

				{% if posts|length > 0 %}
				<header class="major">
					<h2>Search Results for "{{originalsearch}}": </h2>
				</header>
				{% endif %}
				{% if posts|length == 0 %}
				{% if originalsearch|length > 0 %}
				<header class="major">
					<h2>No Results for "{{originalsearch}}": </h2>
				</header>
				{% endif %}
				{% endif %}

				<div class="posts">
					<div class="vertical-articles-container">
						{% for post in posts %}
						<article class="post">
							<a href="#" class="image"><img
									src="{{ url_for('static', filename='images/posts_small/' ~ post.id ~ '.jpg') }}"
									alt="" /></a>
							<header>
								<h3>{{ post.title }}</h3>
								<p>By {{post.author.name}}</p>
							</header>
							<p>{{ post.preview }}</p>
							<ul class="actions">

								<li><a href="{{ url_for('post.show_post', post_id=post.id) }}" class="button">Read</a>
								</li>

							</ul>
						</article>

						{% endfor %}
					</div>
				</div>
				</section>

			</div>
		</div>

		<!-- Sidebar -->
		{% include 'sidebar.html' %}

	</div>

	<script src="{{ url_for('static', filename='assets/js/jquery.min.js') }}"></script>
	<script src="{{ url_for('static', filename='assets/js/browser.min.js') }}"></script>
	<script src="{{ url_for('static', filename='assets/js/breakpoints.min.js') }}"></script>
	<script src="{{ url_for('static', filename='assets/js/util.js') }}"></script>
	<script src="{{ url_for('static', filename='assets/js/main.js') }}"></script>

</body>

</html>

templates/sidebar.html
<script src="{{ url_for('static', filename='jscustom/scripts.js') }}"></script>

<!-- Sidebar -->
<div id="sidebar">
    <div class="inner">

    {% if request.endpoint != 'search.search' %}
    <section id="search" class="alt">
        <div class="search-center">
        <form method="post" action="{{ url_for('search.search') }}">
            {{ searchform.hidden_tag() }}
            {{ searchform.query(placeholder="Search", id="query", required="required", oninput="toggleSearchButton()") }}
            {{ searchform.submit(id="search-btn", style="display:none;" + "margin-top: 5px;") }}
        </form>
        </div>
    </section>
    {% endif %}

        <!-- Menu -->
            <nav id="menu">
                <header class="major">
                    <h2>Site Map</h2>
                    <h3></h3>
                </header>
                <ul>
                    <li><a href="{{ url_for('home.index') }}">Homepage</a></li>
                    <li><a href="{{ url_for('home.mailinglist') }}">Mailing List</a></li>
                    <li><a href="{{ url_for('home.about') }}">About us</a></li>
                    
                </ul>
            </nav>

        <!-- Spotlight Section -->
            <section>
                <header class="major">
                    <h2>Discover {{spotlight_topic}}</h2>
                </header>
                <div class="mini-posts">                  
                    {% for post in spotlight_posts %}
                    <article>
                        <a href="{{ url_for('post.show_post', post_id=post.id) }}" class="image">
                            <img src="{{ url_for('static', filename='images/posts_small/' ~ post.id ~ '.jpg') }}" alt="" />
                        </a>
                        <p>{{post.title}}</p>
                    </article>
                    {% endfor %}
                </div>
            </section>

        <!-- Feedback Section -->
            <section>
                <header class="major">
                    <h2>Get in touch</h2>
                </header>
                <p>We love hearing from our readers and welcome your feedback, questions, and suggestions. Your input is invaluable in helping us continue to deliver content that resonates with you and addresses your interests. Whether you have a specific question for one of our writers, want to share your thoughts on a recent article, or have ideas for topics you'd like to see covered, we're eager to connect and learn from your perspective.</p>
                <ul class="contact">
                    <li class="icon solid fa-envelope"><a href="#">blogueusefeedback@gmail.com</a></li>
                </ul>
            </section>         
            <footer id="footer">
                <p class="copyright">&copy; Untitled. All rights reserved. Stock images from <a href="https://unsplash.com">Unsplash</a></p>
            </footer>
    </div>
</div>